In [1]:
from pathlib import Path

base_dir = Path.cwd().parent
print(base_dir)

c:\Users\kirta\Desktop\IITD

In [2]:
import pandas as pd
pd.set_option('Display.max_colwidth', None)
pd.set_option('Display.max_columns', None)
df = pd.read_csv(f'{base_dir}/meta_csv/5.2_interpretability_and_explainability_meta_results.csv')

In [3]:
print('BASELINE ACCURACY:')
print(df['correct'].sum() / df.shape[0])

print('TOP FLIPPED:')
print(df['top_flipped'].sum())
print('TOP FLIPPED AFTER ACCURACY:')
print((df['top_new_pred'] == df['gold']).sum() / df.shape[0])
print('TOP FLIP RATE:')
print(df['top_flipped'].sum() / df.shape[0])

print('RANDOM FLIPPED:')
print(df['rnd_flipped'].sum())
print('RANDOM FLIPPED AFTER ACCURACY:')
print((df['rnd_new_pred'] == df['gold']).sum() / df.shape[0])
print('RANDOM FLIP RATE:')
print(df['rnd_flipped'].sum() / df.shape[0])

print('TOP DROP MEAN')
print(df['top_drop'].mean())

print('RANDOM DROP MEAN')
print(df['rnd_drop'].mean())

print('TOP MINUS RANDOM MEAN')
print((df['top_drop'] - df['rnd_drop']).mean())

BASELINE ACCURACY:
0.45
TOP FLIPPED:
13
TOP FLIPPED AFTER ACCURACY:
0.35
TOP FLIP RATE:
0.325
RANDOM FLIPPED:
3
RANDOM FLIPPED AFTER ACCURACY:
0.45
RANDOM FLIP RATE:
0.075
TOP DROP MEAN
0.5774811085633701
RANDOM DROP MEAN
0.015595996633055614
TOP MINUS RANDOM MEAN
0.5618851119303144

In [4]:
df[(df['top_new_pred'] != df['gold']) & (df['pred'] == df['gold'])][['top_sentence', 'all_sentences']]

,top_sentence,all_sentences
4,"Since he was promoted to a manager in a large software company 6 months ago, he has had several episodes of these symptoms when he has to give presentations in front of a large group of people.","['A 25-year-old man comes to the physician because of palpitations, sweating, and flushing.', 'Since he was promoted to a manager in a large software company 6 months ago, he has had several episodes of these symptoms when he has to give presentations in front of a large group of people.', 'During these episodes, his thoughts start racing and he fears that his face will “turn red” and everyone will laugh at him.', 'He has tried to avoid the presentations but fears that he might lose his job if he continues to do so.', 'He is healthy except for mild-persistent asthma.', 'He frequently smokes marijuana to calm his nerves.', 'He does not drink alcohol.', 'His only medication is an albuterol inhaler.', 'His pulse is 78/min, respirations are 14/min, and blood pressure is 120/75 mm Hg.', 'Cardiopulmonary examination shows no abnormalities.', 'On mental status examination, the patient appears worried and has a flattened affect.']"
9,"She has hypertension, chronic kidney disease, type 2 diabetes mellitus, and major depressive disorder.","['Two hours after admission to the hospital for dialysis, a 63-year-old woman has severe pain in her lower back.', 'The pain is 8 out of 10 in intensity and radiates down the legs.', 'She underwent a laparoscopic cholecystectomy 4 years ago.', 'She has hypertension, chronic kidney disease, type 2 diabetes mellitus, and major depressive disorder.', 'She lives with her daughter and reports frequent fights with her at home.', 'Her current medications include sertraline, insulin, enalapril, sodium bicarbonate, and sevelamer.', 'She appears uncomfortable.', 'Her temperature is 37.3°C (99.1°F), pulse is 102/min, respirations are 15/min, and blood pressure is 132/94 mm Hg.', 'There is severe tenderness on palpation over the L2 vertebra; range of motion is limited.', 'Neurologic examination shows no focal findings.', 'Laboratory studies show:\nHemoglobin 10.1 g/dL\nLeukocyte count 8,700/mm3\nPlatelet count 130,000/mm3\nSerum\nNa+ 136 mEq/L\nCl- 101 mEq/L\nK+ 5.1 mEq/L\nCalcium 8.2 mg/dL\nUrea nitrogen 33 mg/dL\nGlucose 190 mg/dL\nCreatinine 3.8 mg/dL\nAn x-ray of the spine shows a wedge compression fracture of the L2 vertebra.']"
11,A 63-year-old man comes to the physician for a routine health maintenance examination.,"['A 63-year-old man comes to the physician for a routine health maintenance examination.', 'He feels well.', 'He has a history of hypertension, atrial fibrillation, bipolar disorder, and osteoarthritis of the knees.', 'Current medications include lisinopril, amiodarone, lamotrigine, and acetaminophen.', 'He started amiodarone 6 months ago and switched from lithium to lamotrigine 4 months ago.', 'The patient does not smoke.', 'He drinks 1–4 beers per week.', 'He does not use illicit drugs.', 'Vital signs are within normal limits.', 'Examination shows no abnormalities.']"
14,She also reports increasing fatigue and intermittent tingling in her hands and feet.,"['A 30-year-old caucasian female comes to the physician because of chronic diarrhea and abdominal bloating that started 6 months ago.', 'She also reports increasing fatigue and intermittent tingling in her hands and feet.', 'She lost 5 kg (11 lb) of weight over the past 6 months without changing her diet or trying to lose weight.', 'She and her husband have been trying to conceive for over a year without any success.', 'Menses have been irregular at 28–45 day intervals and last for 1–2 days.', 'She has generalized anxiety disorder for which she takes sertraline.', 'Her height is 151 cm and weight is 50 kg; BMI is 22 kg/m2.', 'Examination shows generalized pallor.', 'Cardiopulmonary examination is normal.', 'Test of the stool for occult blood is negative.']"
33,He says that the Federal Bureau of Investigation has been following him for the last 7 months.,"['A 23-year old man is brought to the emergency department by his brother after trying to jump out of a moving car.', 'He says that the Federal Bureau of Investigation has been following him for the last 7 months.', 'He recently quit his job at a local consulting firm to work on his mission to rid the world from evil.', 'He does not smoke, drink alcoholic beverages, or use illicit drugs.', 'He takes no medications.', 'His temperature is 36.7°C (98.1°F), pulse is 90/min, respirations are 20/min, and blood pressure is 120/86 mm Hg.', 'On mental status examination, his response to the first question lasted 5 minutes without interruption.', 'He switched topics a number of times and his speech was pressured.', 'He spoke excessively about his plan to “bring absolute justice to the world”.', 'He has a labile affect.', 'There is no evidence of suicidal ideation.', 'A toxicology screen is negative.', 'He is admitted to the hospital for his symptoms and starts therapy.', 'One week later, he develops difficulty walking and a tremor that improves with activity.']"
39,A 30-year-old African American woman comes to the physician because of fatigue and muscle weakness for the past 5 weeks.,"['A 30-year-old African American woman comes to the physician because of fatigue and muscle weakness for the past 5 weeks.', 'During this period, she has had recurrent headaches and palpitations.', 'She has hypertension and major depressive disorder.', 'She works as a nurse at a local hospital.', 'She has smoked about 6–8 cigarettes daily for the past 10 years and drinks 1–2 glasses of wine on weekends.', 'Current medications include enalapril, metoprolol, and fluoxetine.', 'She is 160 cm (5 ft 6 in) tall and weighs 60 kg (132 lb); BMI is 21.3 kg/m2.', 'Her temperature is 37°C (98.6°F), pulse is 75/min, and blood pressure is 155/85 mm Hg.', 'The lungs are clear to auscultation.', 'Cardiac examination shows no abnormalities.', 'The abdomen is soft and nontender; bowel sounds are normal.', 'Her skin is dry and there is no edema in the lower extremities.']"

In [5]:
pd.set_option('Display.max_colwidth', None)
df[(df['top_new_pred'] != df['gold']) & (df['pred'] != df['gold'])][['top_sentence', 'all_sentences']]

,top_sentence,all_sentences
1,"Four days after undergoing a coronary artery bypass graft for coronary artery disease, a 60-year-old man complains of abdominal fullness and bloating.","['Four days after undergoing a coronary artery bypass graft for coronary artery disease, a 60-year-old man complains of abdominal fullness and bloating.', 'Since his surgery, he has not had a bowel movement and is unable to pass flatus.', 'He has no nausea or vomiting.', 'Prior to the operation, the patient had daily bowel movements without abnormalities.', 'He has a history of bipolar disorder and hypertension.', 'His current medications include aspirin, atorvastatin, chlorpromazine, amlodipine, and prophylactic subcutaneous heparin.', 'His temperature is 39°C (102.2°F), pulse is 110/min, and blood pressure is 120/80 mm Hg.', 'Cardiopulmonary examination shows no abnormalities.', 'Abdominal examination shows a distended, tympanic abdomen with guarding and rebound tenderness; bowel sounds are hypoactive.', 'Abdominal x-ray shows diffuse distention of the colon loops.', 'A CT scan with contrast confirms the x-ray findings and shows a cecal dilation of 14 cm.']"
2,Both the son's maternal and paternal grandmothers have major depressive disorder.,"['Please refer to the summary above to answer this question\nAn 8-year-old boy is brought to the physician by his mother for a well-child examination at a clinic for low-income residents.', ""Although her son's elementary school offers free afterschool programming, her son has not been interested in attending."", ""Both the son's maternal and paternal grandmothers have major depressive disorder."", ""The mother is curious about the benefits of afterschool programming and asks for the physician's input."", 'Based on the study results, which of the following statements best addresses the mother\'s question?""\n""High-quality afterschool programming during childhood promotes long-term adult mental health\nBackground\nHigh-quality afterschool programming in children has been found to improve standardized test scores, dropout rates, and college attendance.', 'The APPLE (Afterschool Programming for Psychiatric Long-term Endpoints) study seeks to examine the effect of such programs on long-term adult mental health.', 'Design, Setting, and Participants\nSocioeconomically disadvantaged children ages 5–10 were recruited for this study.', 'Participants with a history of intellectual/developmental disability or existing psychiatric illness were excluded.', 'Eligible families were identified by screening government social service agencies in Milwaukee, Wisconsin, and of all qualified families who were invited to participate in free afterschool enrichment activities for their children, 320 children were enrolled.', 'The socioeconomic characteristics of study participants were found to be similar to those of the population being studied.\n160 children were randomly assigned to free afterschool enrichment activities and 160 to a waiting list that served as a control; the parents of 12 children declined participation after their children were randomly assigned to the control group.', ""Of the 83 children participating in the study's 20-year follow-up, 62 were in the treatment group and 21 were in the control group."", 'Interventions\nThe intervention involved free afterschool programming for the first three years of the study.', 'The programming lasted three hours per day and was held five days per week, consisting of an hour of creative problem-based math/reading instruction supplemented with two hours of music, art, and athletic group activities.', 'Children in the control group were placed on the waiting list for the intervention.', ""Main Outcomes and Measures\nData on incidence of common DSM 5-validated mental health conditions was collected at the study's 20-year follow-up evaluation and confirmed by chart review."", 'Results\nTable - Association of major depression, ADHD, bipolar disorder, and psychotic disorder at 20-year follow-up of participants who received afterschool enrichment during childhood*.\n*Adjusted for income and family history of psychiatric illness.', 'Major Depressive Disorder Attention Deficit Hyperactivity Disorder Bipolar Disorder (I or II) without Psychosis Any Psychotic Disorder\nHazard Ratio (95% CI) P -value Hazard Ratio (95% CI) P -value Hazard Ratio (95% CI) P -value Hazard Ratio (95% CI) P -value\nControl 1.0 [reference] -- 1.0 [reference] -- 1.0 [reference] -- 1.0 [reference] --\nAfterschool Enrichment 0.69 (0.59–0.87) < 0.001 0.80 (0.74–0.92) 0.02 0.64 (0.59–1.35) 0.34 0.84 (0.51–1.23) 0.22\nConclusions\nThis study highlights the potential of high-quality afterschool programming during childhood in promoting long-term adult mental health.']"
3,The examination was interrupted multiple times when she became restless and began to walk around the room.,"['A 31-year-old woman is brought to the physician because of increasing restlessness over the past 2 weeks.', 'She reports that she continuously paces around the house and is unable to sit still for more than 10 minutes at a time.', 'During this period, she has had multiple episodes of anxiety with chest tightness and shortness of breath.', 'She was diagnosed with a psychotic illness 2 months ago.', 'Her current medications include haloperidol and a multivitamin.', 'She appears agitated.', 'Vital signs are within normal limits.', 'Physical examination shows no abnormalities.', 'The examination was interrupted multiple times when she became restless and began to walk around the room.']"
5,Physical examination shows a mass in the midepigastric region.,"['A 61-year-old woman with a history of stage IV pancreatic cancer comes to the emergency department with insomnia due to intractable midepigastric pain.', 'The pain had been constant for months but has worsened over the past few weeks despite the fact that she is already taking hydrocodone 10 mg and ibuprofen 400 mg.', 'She has a past medical history of chronic pain and major depressive disorder.', 'In the past month, she has been taking her pain medications with increasing frequency, going from twice a day to four times a day.', 'Her other medications include venlafaxine and eszopiclone.', 'She describes her mood as low, but states she does not have any suicidal thoughts.', 'She appears fatigued and slightly cachectic.', 'Her temperature is 36°C (96.8°F), pulse is 100/min, and blood pressure is 128/65 mm Hg.', 'Physical examination shows a mass in the midepigastric region.']"
8,"The symptoms began after the patient woke up one morning, having slept on his side.","['A 37-year-old man comes to the emergency department with his wife because of a 3-day history of severe pain in his right arm.', 'He also reports that he cannot move his right arm.', 'The symptoms began after the patient woke up one morning, having slept on his side.', 'He is otherwise healthy.', 'He works as a waiter and says that he feels exhausted from working several night shifts per week.', 'He adds that he “can barely keep his eyes open” when looking after their daughter the next day.', 'Since the onset of the pain, he has been unable to work and is fully dependent on his wife, who took an extra shift to make enough money to pay their monthly bills.', 'The patient appears relaxed but only allows himself to be examined after his wife convinces him.', 'His vital signs are within normal limits.', 'Examination shows 1/5 muscle strength in the right arm.', 'Reflexes are normal.', 'He has no sensation to light touch over the entire right arm and forearm.', 'When a pin prick test is conducted, the patient rapidly withdraws the right arm.']"
10,ECG shows prolonged PR intervals and narrow QRS complexes.,"['A 22-year-old woman is brought to the emergency department 4 hours after the ingestion of 25 tablets of an unknown drug in an attempt to commit suicide.', 'Her temperature is 36.7°C (98°F), pulse is 41/min, respirations are 14/min, and blood pressure is 88/55 mm Hg.', 'Pulse oximetry on room air shows an oxygen saturation of 93%.', 'She is confused and oriented only to person.', 'The pupils are equal and reactive to light.', 'Examination shows cold, clammy extremities.', 'Scattered expiratory wheezing and rhonchi are heard throughout both lung fields.', 'The abdomen is soft.', 'Fingerstick blood glucose concentration is 65 mg/dL.', 'ECG shows prolonged PR intervals and narrow QRS complexes.', 'Two large bore cannulas are inserted and intravenous normal saline, dextrose, and atropine are administered.', 'Five minutes later, pulse is 51/min and blood pressure is 95/61 mm Hg.']"
12,"A few minutes later he became tense and his arms and legs began jerking violently, following which he lost consciousness.","['A 38-year-old man is brought to the emergency department 35 minutes after an episode of loss of consciousness.', 'He was having dinner with a client when his left arm suddenly became weak and numb.', 'A few minutes later he became tense and his arms and legs began jerking violently, following which he lost consciousness.', 'He has no recollection of this event.', 'He works as a business consultant.', 'He has a history of asthma and major depressive disorder.', 'Current medication include an albuterol inhaler and doxepin.', 'He increased the dose of doxepin one week ago because he felt the medication was not helping.', 'He drinks two to three beers on the weekend.', 'He admits to using cocaine 4–5 times per week.', 'On arrival, he is alert and oriented to person, place, and time.', 'His speech is slurred.', 'His temperature is 37°C (98.6F), pulse is 96/min, and blood pressure is 155/90 mm Hg.', 'The pupils are equal and reactive to light.', 'Neurologic exam shows left facial droop.', 'There is 3/5 strength in the left arm.']"
13,"A chest x-ray shows symmetrical, diffuse interstitial infiltrates.","['A 37-year-old woman comes to the physician because of a 2-week history of generalized fatigue and malaise.', 'During this period, she has had a non-productive cough with a low-grade fever.', 'Over the past 6 months, she has had a 13-kg (28.6-lb) weight loss and intermittent episodes of watery diarrhea.', 'She has generalized anxiety disorder and hypothyroidism.', 'She has a severe allergy to sulfa drugs.', 'She is sexually active with 3 male partners and uses condoms inconsistently.', 'She has smoked one pack of cigarettes daily for 20 years and drinks 2–3 beers daily.', 'She does not use illicit drugs.', 'Current medications include paroxetine, levothyroxine, and an etonogestrel implant.', 'She is 162.5 cm (5 ft 4 in) tall and weighs 50.3 kg (110.2 lbs); BMI is 19 kg/m2.', 'She appears pale.', 'Her temperature is 38.7°C (101.6°F), pulse is 110/min, and blood pressure is 100/75 mm Hg.', 'Pulse oximetry on room air shows an oxygen saturation of 94%.', 'Examination of the lungs shows bilateral crackles and rhonchi.', 'She has white plaques on the lateral aspect of the tongue that cannot be scraped off.', 'A chest x-ray shows symmetrical, diffuse interstitial infiltrates.']"
15,"About 2 months ago, her psychiatrist switched her medication from aripiprazole to risperidone because it was not effective even at maximum dose.","['A 31-year-old woman comes to the emergency department requesting an abortion.', 'She hears voices telling her that she needs """"to undergo a cleanse."""" She experiences daytime sleepiness because she repeatedly wakes up at night.', 'She says that she is no longer interested in activities that she used to enjoy.', 'About 2 months ago, her psychiatrist switched her medication from aripiprazole to risperidone because it was not effective even at maximum dose.', 'Vital signs are within normal limits.', 'Mental status examination shows accelerated speech, and the patient regularly switches the conversation to the natural habitat of bees.', 'A urine pregnancy test is positive.', 'Toxicology screening is negative.', ""Pelvic ultrasonography shows a pregnancy at an estimated 15 weeks' gestation.""]"
17,Short- and long-term memory is impaired.,"['A 78-year-old man is brought to the physician by his daughter because of increasing forgetfulness over the past 5 weeks.', 'He had been living independently but came to live with his daughter temporarily after he complained that he was unable to perform some of his daily activities.', 'He has left the front door wide open and tap water running on multiple occasions.', 'He does not sleep well and wakes up 6–7 times during the night.', 'He does not leave his room and rarely makes conversation with his daughter.', 'He says that he used to enjoy playing the piano but has not played for several months.', 'He has hypertension treated with amlodipine.', 'Vital signs are within normal limits.', 'Mental status examination shows orientation to person, place, and time and psychomotor retardation.', 'He has a blunted affect.', 'Short- and long-term memory is impaired.', 'Attention and concentration are impaired.', 'Neurologic examination shows no focal findings.', 'Serum concentration of electrolytes, thyroid-stimulating hormone, and vitamin B12 are within the reference range.', 'He is very concerned about his memory lapses.']"
18,"She has a history of a seizure disorder controlled by lamotrigine; other medications include folic acid, iron supplements, and a multivitamin.","[""A 28-year-old woman, gravida 3, para 2, at 12 weeks' gestation comes to the physician for a prenatal visit."", 'She reports feeling fatigued, but she is otherwise feeling well.', 'Pregnancy and delivery of her first 2 children were complicated by iron deficiency anemia.', 'The patient does not smoke or drink alcohol.', 'She does not use illicit drugs.', 'She has a history of a seizure disorder controlled by lamotrigine; other medications include folic acid, iron supplements, and a multivitamin.', 'Her temperature is 37°C (98.6°F), pulse is 80/min, and blood pressure is 144/96 mm Hg.', 'She recalls that during blood pressure self-monitoring yesterday morning her blood pressure was 140/95 mm Hg.', 'Physical examination shows no abnormalities.', 'Laboratory studies, including serum glucose level and thyroid-stimulating hormone concentration, are within normal limits.']"
20,He is diagnosed with Child class B cirrhosis.,"['A 54-year-old man with alcoholism comes to the emergency department because of vomiting blood for 6 hours.', 'He has had 3–4 episodes in which he has vomited dark red blood during this period.', 'He has had no epigastric pain or tarry stools.', 'On arrival, his temperature is 37.3°C (99.1°F), pulse is 134/min, and blood pressure is 80/50 mm Hg.', 'He is resuscitated with 0.9% saline and undergoes an emergency upper endoscopy, which shows actively bleeding varices.', 'Band ligation of the varices is done and hemostasis is achieved.', 'He is diagnosed with Child class B cirrhosis.', 'He is concerned about the possibility of recurrence of such an episode.', 'He is asked to abstain from alcohol, to which he readily agrees.']"
23,A 40-year-old man is brought to the emergency department by police officers due to inappropriate public behavior.,"['A 40-year-old man is brought to the emergency department by police officers due to inappropriate public behavior.', 'He was at a pharmacy demanding to speak with the manager so he could discuss a business deal.', 'Two weeks ago, he left his wife of 10 years and moved from another city in order to pursue his dreams of being an entrepreneur.', 'He has not slept for more than 3-4 hours a night in the last 2 weeks.', 'He has a history of bipolar disorder and diabetes.', 'He has been hospitalized three times in the last year for mood instability.', 'Current medications include lithium and insulin.', 'Mental status examination shows accelerated speech with flight of ideas.', 'His serum creatinine concentration is 2.5 mg/dL.']"
28,She is at the 5th percentile for height and 20th percentile for weight.,"['An 8-year-old girl is brought to the physician for a well-child examination.', 'Since the age of 2 years, she has had multiple fractures after minor trauma.', 'During the past year, she has fractured the left humerus and right clavicle after falls.', 'Her father also has a history of recurrent fractures.', 'She is at the 5th percentile for height and 20th percentile for weight.', 'Vital signs are within normal limits.', 'Physical examination shows increased convexity of the thoracic spine.', 'Forward bend test demonstrates asymmetry of the thoracolumbar region.', 'There is a curvature of the tibias bilaterally, and the left leg is 2 cm longer than the right.', 'There is increased mobility of the joints of the upper and lower extremities.']"
32,"On examination, she does not open her eyes, makes incomprehensible sounds, and extends her extremities when a painful stimulus is applied.","['A 23-year-old woman is brought to the emergency department 30 minutes after being found unresponsive on the floor by her boyfriend.', 'Paramedics found several empty pill bottles next to her on the floor.', 'According to her boyfriend, she has a history of insomnia and generalized anxiety disorder and was recently diagnosed with depression.', 'Her temperature is 36°C (96.8°F), pulse is 64/min, respirations are 10/min and shallow, and blood pressure is 112/75 mm Hg.', 'On examination, she does not open her eyes, makes incomprehensible sounds, and extends her extremities when a painful stimulus is applied.', 'Her pupils are 3 mm and reactive to light.', 'The corneal reflex is normal and gag reflex is absent.', 'There is diffuse hypotonia and decreased deep tendon reflexes.', 'Cardiopulmonary examination shows no abnormalities.', 'She is intubated for airway protection.', 'Mechanical ventilation and an infusion of 0.9% saline are begun.']"
34,The mother is curious about the benefits of afterschool programming and asks for the physician's input.,"['Please refer to the summary above to answer this question\nAn 8-year-old boy is brought to the physician by his mother for a well-child examination at a clinic for low-income residents.', ""Although her son's elementary school offers free afterschool programming, her son has not been interested in attending."", ""Both the son's maternal and paternal grandmothers have major depressive disorder."", ""The mother is curious about the benefits of afterschool programming and asks for the physician's input.""]"
35,"He worries about paying his bills, failing law school, and disappointing his parents.","['A 28-year-old man comes to the physician because of a 9-month history of sleep disturbances, restlessness, and difficulty acquiring erections.', 'He has difficulty falling asleep and wakes up at least 3 times per night.', 'He worries about paying his bills, failing law school, and disappointing his parents.', 'He can no longer concentrate in class and failed the last exam.', 'He feels on edge most days and avoids socializing with his classmates.', 'He worries that he has an underlying medical condition that is causing his symptoms.', 'Previous diagnostic evaluations were unremarkable.', 'There is no personal or family history of serious illness.', 'He is sexually active with his girlfriend.', 'He has a history of drinking alcohol excessively during his early 20s, but he has not consumed alcohol for the past 3 years.', 'He appears anxious.', 'Vital signs are within normal limits.', 'On mental status examination, he is oriented to person, place, and time.', 'Physical examination shows no abnormalities.']"

In [6]:
df[(df['top_new_pred'] == df['gold']) & (df['pred'] != df['gold'])]

,id,n_units,pred,gold,correct,p_pred,top_idx,top_sentence,top_drop,top_flipped,top_new_pred,rnd_idx,rnd_sentence,rnd_drop,rnd_flipped,rnd_new_pred,ctrl_mean_drop,ctrl_flip_rate,all_drops,all_sentences,top_vs_control_diff
30,MEDMISQA_1761,4,F,E,False,0.297864,0,An inpatient psychiatrist recently had two patients who developed serious gastrointestinal infections while taking clozapine.,0.120807,True,E,2,"When the psychiatrist checked the absolute neutrophil count (ANC) of both patients, one was 450/mm3, while the other was 700/mm3 (N=1,500/mm3).",-0.368813,False,F,-0.284630,0.000,"[0.121, -0.116, -0.369, -0.369]","['An inpatient psychiatrist recently had two patients who developed serious gastrointestinal infections while taking clozapine.', 'He was concerned that his patients had developed agranulocytosis, a relatively rare but dangerous adverse event associated with clozapine.', 'When the psychiatrist checked the absolute neutrophil count (ANC) of both patients, one was 450/mm3, while the other was 700/mm3 (N=1,500/mm3).', 'According to the clozapine REMS (Risk Evaluation and Mitigation Strategy) program, severe neutropenia in clozapine recipients has often been defined as an absolute neutrophil count (ANC) less than 500/mm3.']",0.405438
31,MEDMISQA_1756,9,B,C,False,0.661121,8,The physician refers him to an endocrine surgeon.,2.497568,True,C,3,He has a history of multiple kidney stones.,1.942814,True,C,0.131966,0.125,"[-0.275, -0.176, -0.11, 1.943, -0.361, -0.235, -0.265, 0.536, 2.498]","['A 27-year-old man comes to the physician because of worsening abdominal pain over the last several months.', 'He has also had recent feelings of sadness and a lack of motivation at work, where he is employed as a computer programmer.', 'He denies suicidal thoughts.', 'He has a history of multiple kidney stones.', 'He has a family history of thyroid cancer in his father and uncle, who both underwent thyroidectomy before age 30.', 'His temperature is 37°C (98°F), blood pressure is 138/86 mm Hg, and pulse is 87/min.', 'Physical examination shows diffuse tenderness over the abdomen and obesity but is otherwise unremarkable.', 'Serum studies show:\nNa+ 141 mEq/L\nK+ 3.6 mEq/L\nGlucose 144 mg/dL\nCa2+ 12.1 mg/dL\nAlbumin 4.1 g/dL\nPTH 226 pg/mL (normal range 12–88 pg/mL)\nResults of a RET gene test return abnormal.', 'The physician refers him to an endocrine surgeon.']",2.365602

In [7]:
pd.set_option('Display.max_colwidth', None)
df_b = pd.read_csv(f'{base_dir}/meta_csv/5.2_interpretability_before_meta_results.csv')
df_a = pd.read_csv(f'{base_dir}/meta_csv/5.2_interpretability_after_meta_results.csv')

df_b[['answer', 'parsed_answer', 'confidence', 'evidence', 'question', 'top_sentence', 'options']].tail(1)

,answer,parsed_answer,confidence,evidence,question,top_sentence,options
1,C,B,90,"The patient's elevated serum calcium level (12.1 mg/dL) and abnormal PTH level (226 pg/mL) are highly suggestive of primary hyperparathyroidism. The abnormal results of the RET gene test, which is associated with multiple endocrine neoplasia type 2 (MEN2), further supports this diagnosis. A parathyroidectomy is the most appropriate next step in diagnosis to address the hyperparathyroidism and potential MEN2-related complications.","A 27-year-old man comes to the physician because of worsening abdominal pain over the last several months. He has also had recent feelings of sadness and a lack of motivation at work, where he is employed as a computer programmer. He denies suicidal thoughts. He has a history of multiple kidney stones. He has a family history of thyroid cancer in his father and uncle, who both underwent thyroidectomy before age 30. His temperature is 37°C (98°F), blood pressure is 138/86 mm Hg, and pulse is 87/min. Physical examination shows diffuse tenderness over the abdomen and obesity but is otherwise unremarkable. Serum studies show:\nNa+ 141 mEq/L\nK+ 3.6 mEq/L\nGlucose 144 mg/dL\nCa2+ 12.1 mg/dL\nAlbumin 4.1 g/dL\nPTH 226 pg/mL (normal range 12–88 pg/mL)\nResults of a RET gene test return abnormal. The physician refers him to an endocrine surgeon. Which of the following is the most appropriate next step in diagnosis?""",The physician refers him to an endocrine surgeon.,"{'A': 'Thyroidectomy', 'B': 'Parathyroidectomy', 'C': 'Urine metanephrines', 'D': 'Urine 5-HIAA', 'E': 'Midnight salivary cortisol', 'F': 'Serum aldosterone', 'G': 'Serum gastrin'}"

In [8]:
df_a[['answer', 'parsed_answer', 'confidence', 'evidence']].tail(1)

,answer,parsed_answer,confidence,evidence
1,C,C,80,"The patient's symptoms of abdominal pain, recent feelings of sadness and lack of motivation, and the abnormal results of the RET gene test are suggestive of Multiple Endocrine Neoplasia type 2B (MEN2B), a rare genetic disorder that increases the risk of medullary thyroid carcinoma, pheochromocytoma, and hyperparathyroidism. The elevated calcium level (Ca2+ 12.1 mg/dL) and high PTH level (226 pg/mL) are consistent with primary hyperparathyroidism, which is a common feature of MEN2B. Urine metanephrines are a useful screening test for pheochromocytoma, which is a key component of MEN2B."

In [9]:
import pandas as pd
df = pd.read_csv(f'{base_dir}/qwen_csv/5.2_interpretability_and_explainability_qwen_results.csv')

In [10]:
print('BASELINE ACCURACY:')
print(df['correct'].sum() / df.shape[0])

print('TOP FLIPPED:')
print(df['top_flipped'].sum())
print('TOP FLIPPED AFTER ACCURACY:')
print((df['top_new_pred'] == df['gold']).sum() / df.shape[0])
print('TOP FLIP RATE:')
print(df['top_flipped'].sum() / df.shape[0])

print('RANDOM FLIPPED:')
print(df['rnd_flipped'].sum())
print('RANDOM FLIPPED AFTER ACCURACY:')
print((df['rnd_new_pred'] == df['gold']).sum() / df.shape[0])
print('RANDOM FLIP RATE:')
print(df['rnd_flipped'].sum() / df.shape[0])

print('TOP DROP MEAN')
print(df['top_drop'].mean())

print('RANDOM DROP MEAN')
print(df['rnd_drop'].mean())

print('TOP MINUS RANDOM MEAN')
print((df['top_drop'] - df['rnd_drop']).mean())

BASELINE ACCURACY:
0.35
TOP FLIPPED:
18
TOP FLIPPED AFTER ACCURACY:
0.35
TOP FLIP RATE:
0.45
RANDOM FLIPPED:
5
RANDOM FLIPPED AFTER ACCURACY:
0.275
RANDOM FLIP RATE:
0.125
TOP DROP MEAN
1.1966713292619715
RANDOM DROP MEAN
0.12367520486336617
TOP MINUS RANDOM MEAN
1.0729961243986055

In [11]:
df[(df['top_new_pred'] != df['gold']) & (df['pred'] == df['gold'])][['top_sentence', 'all_sentences']]

,top_sentence,all_sentences
0,The patient requests pain medication.,"['29-year-old construction worker is brought to the emergency department after falling 10 ft (3 m) from the scaffolding at a construction site.', 'He reports that he landed on his outstretched arms, which are now in severe pain (10/10 on a numeric scale).', 'He has a history of opioid use disorder and is currently on methadone maintenance treatment.', 'His pulse is 100/min, respirations are 20/min, and blood pressure is 140/90 mm Hg.', 'Pulse oximetry on room air shows an oxygen saturation of 98%.', 'He is diaphoretic and in distress.', ""Physical examination shows a hematoma on the patient's right forearm."", 'X-ray of the right arm shows a nondisplaced fracture of the ulna.', 'A CT of the abdomen and pelvis shows no abnormalities.', 'The patient requests pain medication.']"
6,He refuses cognitive behavioral therapy and is started on sertraline.,"['A 32-year-old man comes to the Veterans Affairs hospital because of difficulty sleeping for the past 9 weeks.', 'He is a soldier who returned from a deployment in Afghanistan 12 weeks ago.', 'Fifteen weeks ago, his unit was ambushed in a deserted street, and a fellow soldier was killed.', 'He wakes up frequently during the night from vivid dreams of this incident.', 'He blames himself for being unable to save his friend.', 'He also has trouble falling asleep and gets up earlier than desired.', 'During this period, he has started to avoid walking in deserted streets.', 'Vital signs are within normal limits.', 'Physical examination shows no abnormalities.', 'He refuses cognitive behavioral therapy and is started on sertraline.', 'Five weeks later, he returns to the physician and complains about persistent nightmares and difficulty sleeping.']"
9,"She has hypertension, chronic kidney disease, type 2 diabetes mellitus, and major depressive disorder.","['Two hours after admission to the hospital for dialysis, a 63-year-old woman has severe pain in her lower back.', 'The pain is 8 out of 10 in intensity and radiates down the legs.', 'She underwent a laparoscopic cholecystectomy 4 years ago.', 'She has hypertension, chronic kidney disease, type 2 diabetes mellitus, and major depressive disorder.', 'She lives with her daughter and reports frequent fights with her at home.', 'Her current medications include sertraline, insulin, enalapril, sodium bicarbonate, and sevelamer.', 'She appears uncomfortable.', 'Her temperature is 37.3°C (99.1°F), pulse is 102/min, respirations are 15/min, and blood pressure is 132/94 mm Hg.', 'There is severe tenderness on palpation over the L2 vertebra; range of motion is limited.', 'Neurologic examination shows no focal findings.', 'Laboratory studies show:\nHemoglobin 10.1 g/dL\nLeukocyte count 8,700/mm3\nPlatelet count 130,000/mm3\nSerum\nNa+ 136 mEq/L\nCl- 101 mEq/L\nK+ 5.1 mEq/L\nCalcium 8.2 mg/dL\nUrea nitrogen 33 mg/dL\nGlucose 190 mg/dL\nCreatinine 3.8 mg/dL\nAn x-ray of the spine shows a wedge compression fracture of the L2 vertebra.']"
23,He has not slept for more than 3-4 hours a night in the last 2 weeks.,"['A 40-year-old man is brought to the emergency department by police officers due to inappropriate public behavior.', 'He was at a pharmacy demanding to speak with the manager so he could discuss a business deal.', 'Two weeks ago, he left his wife of 10 years and moved from another city in order to pursue his dreams of being an entrepreneur.', 'He has not slept for more than 3-4 hours a night in the last 2 weeks.', 'He has a history of bipolar disorder and diabetes.', 'He has been hospitalized three times in the last year for mood instability.', 'Current medications include lithium and insulin.', 'Mental status examination shows accelerated speech with flight of ideas.', 'His serum creatinine concentration is 2.5 mg/dL.']"
36,She has smoked one pack of cigarettes daily for 7 years.,"['A 22-year-old woman comes to the physician for a routine health examination.', 'She feels well but asks for advice about smoking cessation.', 'She has smoked one pack of cigarettes daily for 7 years.', 'She has tried to quit several times without success.', 'During the previous attempts, she has been extremely nervous and also gained weight.', 'She has also tried nicotine lozenges but stopped taking them because of severe headaches and insomnia.', 'She has bulimia nervosa.', 'She takes no medications.', 'She is 168 cm (5 ft 6 in) tall and weighs 68 kg (150 lb); BMI is 24 kg/m2.', 'Physical and neurologic examinations show no other abnormalities.']"

In [12]:
df[(df['top_new_pred'] != df['gold']) & (df['pred'] != df['gold'])][['top_sentence', 'all_sentences']]

,top_sentence,all_sentences
3,She reports that she continuously paces around the house and is unable to sit still for more than 10 minutes at a time.,"['A 31-year-old woman is brought to the physician because of increasing restlessness over the past 2 weeks.', 'She reports that she continuously paces around the house and is unable to sit still for more than 10 minutes at a time.', 'During this period, she has had multiple episodes of anxiety with chest tightness and shortness of breath.', 'She was diagnosed with a psychotic illness 2 months ago.', 'Her current medications include haloperidol and a multivitamin.', 'She appears agitated.', 'Vital signs are within normal limits.', 'Physical examination shows no abnormalities.', 'The examination was interrupted multiple times when she became restless and began to walk around the room.']"
5,The pain had been constant for months but has worsened over the past few weeks despite the fact that she is already taking hydrocodone 10 mg and ibuprofen 400 mg.,"['A 61-year-old woman with a history of stage IV pancreatic cancer comes to the emergency department with insomnia due to intractable midepigastric pain.', 'The pain had been constant for months but has worsened over the past few weeks despite the fact that she is already taking hydrocodone 10 mg and ibuprofen 400 mg.', 'She has a past medical history of chronic pain and major depressive disorder.', 'In the past month, she has been taking her pain medications with increasing frequency, going from twice a day to four times a day.', 'Her other medications include venlafaxine and eszopiclone.', 'She describes her mood as low, but states she does not have any suicidal thoughts.', 'She appears fatigued and slightly cachectic.', 'Her temperature is 36°C (96.8°F), pulse is 100/min, and blood pressure is 128/65 mm Hg.', 'Physical examination shows a mass in the midepigastric region.']"
7,She also reports having dry mouth and feeling thirsty all the time despite drinking several liters of water per day.,"['A 30-year-old woman comes to the physician because of increased urinary frequency over the past month.', 'She also reports having dry mouth and feeling thirsty all the time despite drinking several liters of water per day.', 'She has not had any weight changes and her appetite is normal.', 'She has a history of obsessive compulsive disorder treated with citalopram.', 'She drinks 1–2 cans of beer per day.', 'Her vital signs are within normal limits.', 'Physical examination shows no abnormalities.', 'Laboratory studies show:\nSerum\nNa+ 130 mEq/L\nGlucose 110 mg/dL\nOsmolality 265 mOsmol/kg\nUrine\nOsmolality 230 mOsmol/kg\nThe patient is asked to stop drinking water for 3 hours.', 'Following water restriction, urine osmolality is measured every hour, whereas serum osmolality is measured every 2 hours.', 'Repeated laboratory measurements show a serum osmolality of 280 mOsmol/kg and a urine osmolality of 650 mOsmol/kg.']"
12,"A few minutes later he became tense and his arms and legs began jerking violently, following which he lost consciousness.","['A 38-year-old man is brought to the emergency department 35 minutes after an episode of loss of consciousness.', 'He was having dinner with a client when his left arm suddenly became weak and numb.', 'A few minutes later he became tense and his arms and legs began jerking violently, following which he lost consciousness.', 'He has no recollection of this event.', 'He works as a business consultant.', 'He has a history of asthma and major depressive disorder.', 'Current medication include an albuterol inhaler and doxepin.', 'He increased the dose of doxepin one week ago because he felt the medication was not helping.', 'He drinks two to three beers on the weekend.', 'He admits to using cocaine 4–5 times per week.', 'On arrival, he is alert and oriented to person, place, and time.', 'His speech is slurred.', 'His temperature is 37°C (98.6F), pulse is 96/min, and blood pressure is 155/90 mm Hg.', 'The pupils are equal and reactive to light.', 'Neurologic exam shows left facial droop.', 'There is 3/5 strength in the left arm.']"
13,A 37-year-old woman comes to the physician because of a 2-week history of generalized fatigue and malaise.,"['A 37-year-old woman comes to the physician because of a 2-week history of generalized fatigue and malaise.', 'During this period, she has had a non-productive cough with a low-grade fever.', 'Over the past 6 months, she has had a 13-kg (28.6-lb) weight loss and intermittent episodes of watery diarrhea.', 'She has generalized anxiety disorder and hypothyroidism.', 'She has a severe allergy to sulfa drugs.', 'She is sexually active with 3 male partners and uses condoms inconsistently.', 'She has smoked one pack of cigarettes daily for 20 years and drinks 2–3 beers daily.', 'She does not use illicit drugs.', 'Current medications include paroxetine, levothyroxine, and an etonogestrel implant.', 'She is 162.5 cm (5 ft 4 in) tall and weighs 50.3 kg (110.2 lbs); BMI is 19 kg/m2.', 'She appears pale.', 'Her temperature is 38.7°C (101.6°F), pulse is 110/min, and blood pressure is 100/75 mm Hg.', 'Pulse oximetry on room air shows an oxygen saturation of 94%.', 'Examination of the lungs shows bilateral crackles and rhonchi.', 'She has white plaques on the lateral aspect of the tongue that cannot be scraped off.', 'A chest x-ray shows symmetrical, diffuse interstitial infiltrates.']"
15,Pelvic ultrasonography shows a pregnancy at an estimated 15 weeks' gestation.,"['A 31-year-old woman comes to the emergency department requesting an abortion.', 'She hears voices telling her that she needs """"to undergo a cleanse."""" She experiences daytime sleepiness because she repeatedly wakes up at night.', 'She says that she is no longer interested in activities that she used to enjoy.', 'About 2 months ago, her psychiatrist switched her medication from aripiprazole to risperidone because it was not effective even at maximum dose.', 'Vital signs are within normal limits.', 'Mental status examination shows accelerated speech, and the patient regularly switches the conversation to the natural habitat of bees.', 'A urine pregnancy test is positive.', 'Toxicology screening is negative.', ""Pelvic ultrasonography shows a pregnancy at an estimated 15 weeks' gestation.""]"
16,A 24-year-old woman is brought to the emergency department by her roommate because of bizarre behavior and incoherent talkativeness for the past week.,"['A 24-year-old woman is brought to the emergency department by her roommate because of bizarre behavior and incoherent talkativeness for the past week.', 'Her roommate reports that the patient has been rearranging the furniture in her room at night and has ordered a variety of expensive clothes online.', 'The patient says she feels “better than ever” and has a lot of energy.', 'She had absence seizures as a child and remembers that valproate had to be discontinued because it damaged her liver.', 'She has been otherwise healthy and is not taking any medication.', 'She is sexually active with her boyfriend.', 'She does not smoke, drink alcohol, or use illicit drugs.', 'Physical and neurologic examinations show no abnormalities.', 'Her pulse is 78/min, respirations are 13/min, and blood pressure is 122/60 mm Hg.', 'Mental status examination shows pressured and disorganized speech, flight of ideas, lack of insight, and affective lability.']"
17,A 78-year-old man is brought to the physician by his daughter because of increasing forgetfulness over the past 5 weeks.,"['A 78-year-old man is brought to the physician by his daughter because of increasing forgetfulness over the past 5 weeks.', 'He had been living independently but came to live with his daughter temporarily after he complained that he was unable to perform some of his daily activities.', 'He has left the front door wide open and tap water running on multiple occasions.', 'He does not sleep well and wakes up 6–7 times during the night.', 'He does not leave his room and rarely makes conversation with his daughter.', 'He says that he used to enjoy playing the piano but has not played for several months.', 'He has hypertension treated with amlodipine.', 'Vital signs are within normal limits.', 'Mental status examination shows orientation to person, place, and time and psychomotor retardation.', 'He has a blunted affect.', 'Short- and long-term memory is impaired.', 'Attention and concentration are impaired.', 'Neurologic examination shows no focal findings.', 'Serum concentration of electrolytes, thyroid-stimulating hormone, and vitamin B12 are within the reference range.', 'He is very concerned about his memory lapses.']"
20,A 54-year-old man with alcoholism comes to the emergency department because of vomiting blood for 6 hours.,"['A 54-year-old man with alcoholism comes to the emergency department because of vomiting blood for 6 hours.', 'He has had 3–4 episodes in which he has vomited dark red blood during this period.', 'He has had no epigastric pain or tarry stools.', 'On arrival, his temperature is 37.3°C (99.1°F), pulse is 134/min, and blood pressure is 80/50 mm Hg.', 'He is resuscitated with 0.9% saline and undergoes an emergency upper endoscopy, which shows actively bleeding varices.', 'Band ligation of the varices is done and hemostasis is achieved.', 'He is diagnosed with Child class B cirrhosis.', 'He is concerned about the possibility of recurrence of such an episode.', 'He is asked to abstain from alcohol, to which he readily agrees.']"
21,Both serum cortisol and ACTH levels are decreased.,"['A 69-year-old woman is brought to the emergency department because of fatigue and lethargy for 5 days.', 'She has also had weakness and nausea for the last 3 days.', 'She has sarcoidosis, major depressive disorder, and hypertension.', 'She had a stroke 5 years ago.', 'Current medications include aspirin, nifedipine, prednisolone, fluoxetine, and rosuvastatin, but she has not taken any of her medications for 7 days due to international travel.', 'Her temperature is 36.1°C (96.9°F), pulse is 95/min, and blood pressure is 85/65 mm Hg.', 'She is lethargic but oriented.', 'Examination shows no other abnormalities.', 'Her hemoglobin concentration is 13.4 g/dL and leukocyte count is 9,600/mm3.', 'Both serum cortisol and ACTH levels are decreased.']"
22,"A 60-year-old man comes to the emergency department because of recurrent episodes of fatigue, palpitations, nausea, and diaphoresis over the past 6 months.","['A 60-year-old man comes to the emergency department because of recurrent episodes of fatigue, palpitations, nausea, and diaphoresis over the past 6 months.', 'The episodes have become more frequent in the last 2 weeks and he has missed work several times because of them.', 'His symptoms usually improve after he drinks some juice and rests.', 'He has had a 2-kg (4.5-lb) weight gain in the past 6 months.', 'He has a history of bipolar disorder, hypertension, and asthma.', 'His sister has type 2 diabetes mellitus and his mother has a history of medullary thyroid carcinoma.', 'His medications include lithium, hydrochlorothiazide, aspirin, and a budesonide inhaler.', 'His temperature is 36.3°C (97.3°F), pulse is 92/min and regular, respirations are 20/min, and blood pressure is 118/65 mm Hg.', 'Abdominal examination shows no abnormalities.']"
24,He has bipolar disorder with psychotic features and hypothyroidism.,"['A 31-year-old man is brought to the emergency department because of fever and increasing confusion for the past day.', 'He has bipolar disorder with psychotic features and hypothyroidism.', 'Current medications are lithium, haloperidol, and levothyroxine.', 'He drinks one beer with dinner every night.', 'His speech is confused and he is oriented to person only.', 'His temperature is 40°C (104°F), pulse is 124/min, and blood pressure is 160/110 mm Hg.', 'He appears acutely ill.', 'Examination shows diaphoresis and muscle rigidity.', 'Deep tendon reflexes are 1+ bilaterally.', 'There is minor rigidity of the neck with full range of motion.', 'His lungs are clear to auscultation.', 'The abdomen is soft and nontender.', 'His leukocyte count is 15,100/mm3 and serum creatine kinase activity is 1100 U/L.']"
25,She is looking at a list of HCC patients on her hospital's hepatology consult service and trying to identify candidates who might derive more survival benefits from Noxbinle as opposed to Metalimus.,"['A hepatologist has learned about the survival benefit of Noxbinle (tumorolimus) in hepatocellular carcinoma (HCC) patients from a fellow physician.', ""She is looking at a list of HCC patients on her hospital's hepatology consult service and trying to identify candidates who might derive more survival benefits from Noxbinle as opposed to Metalimus.""]"
28,Her father also has a history of recurrent fractures.,"['An 8-year-old girl is brought to the physician for a well-child examination.', 'Since the age of 2 years, she has had multiple fractures after minor trauma.', 'During the past year, she has fractured the left humerus and right clavicle after falls.', 'Her father also has a history of recurrent fractures.', 'She is at the 5th percentile for height and 20th percentile for weight.', 'Vital signs are within normal limits.', 'Physical examination shows increased convexity of the thoracic spine.', 'Forward bend test demonstrates asymmetry of the thoracolumbar region.', 'There is a curvature of the tibias bilaterally, and the left leg is 2 cm longer than the right.', 'There is increased mobility of the joints of the upper and lower extremities.']"
30,"He was concerned that his patients had developed agranulocytosis, a relatively rare but dangerous adverse event associated with clozapine.","['An inpatient psychiatrist recently had two patients who developed serious gastrointestinal infections while taking clozapine.', 'He was concerned that his patients had developed agranulocytosis, a relatively rare but dangerous adverse event associated with clozapine.', 'When the psychiatrist checked the absolute neutrophil count (ANC) of both patients, one was 450/mm3, while the other was 700/mm3 (N=1,500/mm3).', 'According to the clozapine REMS (Risk Evaluation and Mitigation Strategy) program, severe neutropenia in clozapine recipients has often been defined as an absolute neutrophil count (ANC) less than 500/mm3.']"
31,Serum studies show:\nNa+ 141 mEq/L\nK+ 3.6 mEq/L\nGlucose 144 mg/dL\nCa2+ 12.1 mg/dL\nAlbumin 4.1 g/dL\nPTH 226 pg/mL (normal range 12–88 pg/mL)\nResults of a RET gene test return abnormal.,"['A 27-year-old man comes to the physician because of worsening abdominal pain over the last several months.', 'He has also had recent feelings of sadness and a lack of motivation at work, where he is employed as a computer programmer.', 'He denies suicidal thoughts.', 'He has a history of multiple kidney stones.', 'He has a family history of thyroid cancer in his father and uncle, who both underwent thyroidectomy before age 30.', 'His temperature is 37°C (98°F), blood pressure is 138/86 mm Hg, and pulse is 87/min.', 'Physical examination shows diffuse tenderness over the abdomen and obesity but is otherwise unremarkable.', 'Serum studies show:\nNa+ 141 mEq/L\nK+ 3.6 mEq/L\nGlucose 144 mg/dL\nCa2+ 12.1 mg/dL\nAlbumin 4.1 g/dL\nPTH 226 pg/mL (normal range 12–88 pg/mL)\nResults of a RET gene test return abnormal.', 'The physician refers him to an endocrine surgeon.']"
32,Paramedics found several empty pill bottles next to her on the floor.,"['A 23-year-old woman is brought to the emergency department 30 minutes after being found unresponsive on the floor by her boyfriend.', 'Paramedics found several empty pill bottles next to her on the floor.', 'According to her boyfriend, she has a history of insomnia and generalized anxiety disorder and was recently diagnosed with depression.', 'Her temperature is 36°C (96.8°F), pulse is 64/min, respirations are 10/min and shallow, and blood pressure is 112/75 mm Hg.', 'On examination, she does not open her eyes, makes incomprehensible sounds, and extends her extremities when a painful stimulus is applied.', 'Her pupils are 3 mm and reactive to light.', 'The corneal reflex is normal and gag reflex is absent.', 'There is diffuse hypotonia and decreased deep tendon reflexes.', 'Cardiopulmonary examination shows no abnormalities.', 'She is intubated for airway protection.', 'Mechanical ventilation and an infusion of 0.9% saline are begun.']"
33,"One week later, he develops difficulty walking and a tremor that improves with activity.","['A 23-year old man is brought to the emergency department by his brother after trying to jump out of a moving car.', 'He says that the Federal Bureau of Investigation has been following him for the last 7 months.', 'He recently quit his job at a local consulting firm to work on his mission to rid the world from evil.', 'He does not smoke, drink alcoholic beverages, or use illicit drugs.', 'He takes no medications.', 'His temperature is 36.7°C (98.1°F), pulse is 90/min, respirations are 20/min, and blood pressure is 120/86 mm Hg.', 'On mental status examination, his response to the first question lasted 5 minutes without interruption.', 'He switched topics a number of times and his speech was pressured.', 'He spoke excessively about his plan to “bring absolute justice to the world”.', 'He has a labile affect.', 'There is no evidence of suicidal ideation.', 'A toxicology screen is negative.', 'He is admitted to the hospital for his symptoms and starts therapy.', 'One week later, he develops difficulty walking and a tremor that improves with activity.']"
35,"A 28-year-old man comes to the physician because of a 9-month history of sleep disturbances, restlessness, and difficulty acquiring erections.","['A 28-year-old man comes to the physician because of a 9-month history of sleep disturbances, restlessness, and difficulty acquiring erections.', 'He has difficulty falling asleep and wakes up at least 3 times per night.', 'He worries about paying his bills, failing law school, and disappointing his parents.', 'He can no longer concentrate in class and failed the last exam.', 'He feels on edge most days and avoids socializing with his classmates.', 'He worries that he has an underlying medical condition that is causing his symptoms.', 'Previous diagnostic evaluations were unremarkable.', 'There is no personal or family history of serious illness.', 'He is sexually active with his girlfriend.', 'He has a history of drinking alcohol excessively during his early 20s, but he has not consumed alcohol for the past 3 years.', 'He appears anxious.', 'Vital signs are within normal limits.', 'On mental status examination, he is oriented to person, place, and time.', 'Physical examination shows no abnormalities.']"

In [13]:
df[(df['top_new_pred'] == df['gold']) & (df['pred'] != df['gold'])]

,id,n_units,pred,gold,correct,p_pred,top_idx,top_sentence,top_drop,top_flipped,top_new_pred,rnd_idx,rnd_sentence,rnd_drop,rnd_flipped,rnd_new_pred,ctrl_mean_drop,ctrl_flip_rate,all_drops,all_sentences,top_vs_control_diff
2,MEDMISQA_217,17,E,H,False,0.684154,4,"Based on the study results, which of the following statements best addresses the mother's question?""\n""High-quality afterschool programming during childhood promotes long-term adult mental health\nBackground\nHigh-quality afterschool programming in children has been found to improve standardized test scores, dropout rates, and college attendance.",4.635557,True,H,13,Children in the control group were placed on the waiting list for the intervention.,0.054867,False,E,0.378705,0.312500,"[-0.362, -0.317, 3.496, -0.17, 4.636, 0.436, 0.336, 0.181, -0.001, 0.151, 0.452, 0.229, 0.597, 0.055, 0.673, -0.119, 0.422]","['Please refer to the summary above to answer this question\nAn 8-year-old boy is brought to the physician by his mother for a well-child examination at a clinic for low-income residents.', ""Although her son's elementary school offers free afterschool programming, her son has not been interested in attending."", ""Both the son's maternal and paternal grandmothers have major depressive disorder."", ""The mother is curious about the benefits of afterschool programming and asks for the physician's input."", 'Based on the study results, which of the following statements best addresses the mother\'s question?""\n""High-quality afterschool programming during childhood promotes long-term adult mental health\nBackground\nHigh-quality afterschool programming in children has been found to improve standardized test scores, dropout rates, and college attendance.', 'The APPLE (Afterschool Programming for Psychiatric Long-term Endpoints) study seeks to examine the effect of such programs on long-term adult mental health.', 'Design, Setting, and Participants\nSocioeconomically disadvantaged children ages 5–10 were recruited for this study.', 'Participants with a history of intellectual/developmental disability or existing psychiatric illness were excluded.', 'Eligible families were identified by screening government social service agencies in Milwaukee, Wisconsin, and of all qualified families who were invited to participate in free afterschool enrichment activities for their children, 320 children were enrolled.', 'The socioeconomic characteristics of study participants were found to be similar to those of the population being studied.\n160 children were randomly assigned to free afterschool enrichment activities and 160 to a waiting list that served as a control; the parents of 12 children declined participation after their children were randomly assigned to the control group.', ""Of the 83 children participating in the study's 20-year follow-up, 62 were in the treatment group and 21 were in the control group."", 'Interventions\nThe intervention involved free afterschool programming for the first three years of the study.', 'The programming lasted three hours per day and was held five days per week, consisting of an hour of creative problem-based math/reading instruction supplemented with two hours of music, art, and athletic group activities.', 'Children in the control group were placed on the waiting list for the intervention.', ""Main Outcomes and Measures\nData on incidence of common DSM 5-validated mental health conditions was collected at the study's 20-year follow-up evaluation and confirmed by chart review."", 'Results\nTable - Association of major depression, ADHD, bipolar disorder, and psychotic disorder at 20-year follow-up of participants who received afterschool enrichment during childhood*.\n*Adjusted for income and family history of psychiatric illness.', 'Major Depressive Disorder Attention Deficit Hyperactivity Disorder Bipolar Disorder (I or II) without Psychosis Any Psychotic Disorder\nHazard Ratio (95% CI) P -value Hazard Ratio (95% CI) P -value Hazard Ratio (95% CI) P -value Hazard Ratio (95% CI) P -value\nControl 1.0 [reference] -- 1.0 [reference] -- 1.0 [reference] -- 1.0 [reference] --\nAfterschool Enrichment 0.69 (0.59–0.87) < 0.001 0.80 (0.74–0.92) 0.02 0.64 (0.59–1.35) 0.34 0.84 (0.51–1.23) 0.22\nConclusions\nThis study highlights the potential of high-quality afterschool programming during childhood in promoting long-term adult mental health.']",4.256853
8,MEDMISQA_502,13,E,D,False,0.435728,2,"The symptoms began after the patient woke up one morning, having slept on his side.",1.688344,True,D,11,He has no sensation to light touch over the entire right arm and forearm.,0.269260,True,G,-0.141559,0.166667,"[-0.763, -0.362, 1.688, -0.027, -0.235, 0.499, -0.561, -0.535, -0.058, 0.086, 0.223, 0.269, -0.235]","['A 37-year-old man comes to the emergency department with his wife because of a 3-day history of severe pain in his right arm.', 'He also reports that he cannot move his right arm.', 'The symptoms began after the patient woke up one morning, having slept on his side.', 'He is otherwise healthy.', 'He works as a waiter and says that he feels exhausted from working several night shifts per week.', 'He adds that he “can barely keep his eyes open” when looking after their daughter the next day.', 'Since the onset of the pain, he has been unable to work and is fully dependent on his wife, who took an extra shift to make enough money to pay their monthly bills.', 'The patient appears relaxed but only allows himself to be examined after his wife convinces him.', 'His vital signs are within normal limits.', 'Examination shows 1/5 muscle strength in the right arm.', 'Reflexes are normal.', 'He has no sensation to light touch over the entire right arm and forearm.', 'When a pin prick test is conducted, the patient rapidly withdraws the right arm.']",1.829903
10,MEDMISQA_655,12,F,A,False,0.762274,0,A 22-year-old woman is brought to the emergency department 4 hours after the ingestion of 25 tablets of an unknown drug in an attempt to commit suicide.,1.564830,True,A,9,ECG shows prolonged PR intervals and narrow QRS complexes.,0.114925,False,F,0.042780,0.000000,"[1.565, 0.138, -0.027, 0.044, 0.031, 0.093, -0.146, 0.079, 0.076, 0.115, -0.108, 0.175]","['A 22-year-old woman is brought to the emergency department 4 hours after the ingestion of 25 tablets of an unknown drug in an attempt to commit suicide.', 'Her temperature is 36.7°C (98°F), pulse is 41/min, respirations are 14/min, and blood pressure is 88/55 mm Hg.', 'Pulse oximetry on room air shows an oxygen saturation of 93%.', 'She is confused and oriented only to person.', 'The pupils are equal and reactive to light.', 'Examination shows cold, clammy extremities.', 'Scattered expiratory wheezing and rhonchi are heard throughout both lung fields.', 'The abdomen is soft.', 'Fingerstick blood glucose concentration is 65 mg/dL.', 'ECG shows prolonged PR intervals and narrow QRS complexes.', 'Two large bore cannulas are inserted and intravenous normal saline, dextrose, and atropine are administered.', 'Five minutes later, pulse is 51/min and blood pressure is 95/61 mm Hg.']",1.522050
11,MEDMISQA_718,10,C,B,False,0.549736,3,"Current medications include lisinopril, amiodarone, lamotrigine, and acetaminophen.",0.608604,True,B,7,He does not use illicit drugs.,-0.086558,False,C,0.075932,0.333333,"[-0.158, 0.041, 0.185, 0.609, 0.041, 0.102, 0.31, -0.087, 0.022, 0.226]","['A 63-year-old man comes to the physician for a routine health maintenance examination.', 'He feels well.', 'He has a history of hypertension, atrial fibrillation, bipolar disorder, and osteoarthritis of the knees.', 'Current medications include lisinopril, amiodarone, lamotrigine, and acetaminophen.', 'He started amiodarone 6 months ago and switched from lithium to lamotrigine 4 months ago.', 'The patient does not smoke.', 'He drinks 1–4 beers per week.', 'He does not use illicit drugs.', 'Vital signs are within normal limits.', 'Examination shows no abnormalities.']",0.532672
27,MEDMISQA_1680,5,D,B,False,0.913340,0,A patient with HCC and a long history of alcohol dependence and chronic hepatitis C has been using the mTOR inhibitor Metalimus 100 mg for cancer treatment.,3.177356,True,B,2,She also has a history of hypertension and poorly controlled type 2 diabetes mellitus complicated by diabetic retinopathy.,-0.013344,False,D,0.060590,0.000000,"[3.177, 0.015, -0.013, -0.053, 0.294]","['A patient with HCC and a long history of alcohol dependence and chronic hepatitis C has been using the mTOR inhibitor Metalimus 100 mg for cancer treatment.', 'Her cancer has shown a partial response.', 'She also has a history of hypertension and poorly controlled type 2 diabetes mellitus complicated by diabetic retinopathy.', 'Current medications include enalapril and insulin.', 'She asks her oncologist and hepatologist if she could try Noxbinle (tumorolimus) for its purported survival benefit in treating HCC.']",3.116766

In [14]:
df_b = pd.read_csv(f'{base_dir}/qwen_csv/5.2_interpretability_before_qwen_results.csv')
df_a = pd.read_csv(f'{base_dir}/qwen_csv/5.2_interpretability_after_qwen_results.csv')

df_b[['answer', 'parsed_answer', 'confidence', 'evidence', 'question', 'top_sentence', 'options']]

,answer,parsed_answer,confidence,evidence,question,top_sentence,options
0,H,E,100,"The study results clearly show that high-quality afterschool programming during childhood reduces the risk of major depressive disorder in adults. Specifically, the hazard ratio for major depressive disorder in the afterschool enrichment group was 0.69 (95% CI: 0.59–0.87), indicating a statistically significant reduction compared to the control group. This aligns perfectly with option E, making it the most accurate statement based on the provided information.","Please refer to the summary above to answer this question\nAn 8-year-old boy is brought to the physician by his mother for a well-child examination at a clinic for low-income residents. Although her son's elementary school offers free afterschool programming, her son has not been interested in attending. Both the son's maternal and paternal grandmothers have major depressive disorder. The mother is curious about the benefits of afterschool programming and asks for the physician's input. Based on the study results, which of the following statements best addresses the mother's question?""\n""High-quality afterschool programming during childhood promotes long-term adult mental health\nBackground\nHigh-quality afterschool programming in children has been found to improve standardized test scores, dropout rates, and college attendance. The APPLE (Afterschool Programming for Psychiatric Long-term Endpoints) study seeks to examine the effect of such programs on long-term adult mental health.\nDesign, Setting, and Participants\nSocioeconomically disadvantaged children ages 5–10 were recruited for this study. Participants with a history of intellectual/developmental disability or existing psychiatric illness were excluded. Eligible families were identified by screening government social service agencies in Milwaukee, Wisconsin, and of all qualified families who were invited to participate in free afterschool enrichment activities for their children, 320 children were enrolled. The socioeconomic characteristics of study participants were found to be similar to those of the population being studied.\n160 children were randomly assigned to free afterschool enrichment activities and 160 to a waiting list that served as a control; the parents of 12 children declined participation after their children were randomly assigned to the control group. Of the 83 children participating in the study's 20-year follow-up, 62 were in the treatment group and 21 were in the control group.\nInterventions\nThe intervention involved free afterschool programming for the first three years of the study. The programming lasted three hours per day and was held five days per week, consisting of an hour of creative problem-based math/reading instruction supplemented with two hours of music, art, and athletic group activities. Children in the control group were placed on the waiting list for the intervention.\nMain Outcomes and Measures\nData on incidence of common DSM 5-validated mental health conditions was collected at the study's 20-year follow-up evaluation and confirmed by chart review.\nResults\nTable - Association of major depression, ADHD, bipolar disorder, and psychotic disorder at 20-year follow-up of participants who received afterschool enrichment during childhood*.\n*Adjusted for income and family history of psychiatric illness.\nMajor Depressive Disorder Attention Deficit Hyperactivity Disorder Bipolar Disorder (I or II) without Psychosis Any Psychotic Disorder\nHazard Ratio (95% CI) P -value Hazard Ratio (95% CI) P -value Hazard Ratio (95% CI) P -value Hazard Ratio (95% CI) P -value\nControl 1.0 [reference] -- 1.0 [reference] -- 1.0 [reference] -- 1.0 [reference] --\nAfterschool Enrichment 0.69 (0.59–0.87) < 0.001 0.80 (0.74–0.92) 0.02 0.64 (0.59–1.35) 0.34 0.84 (0.51–1.23) 0.22\nConclusions\nThis study highlights the potential of high-quality afterschool programming during childhood in promoting long-term adult mental health.\nSource of funding: Wisconsin Children's Mental Health Foundation, National Early Childhood Education Coalition""","Based on the study results, which of the following statements best addresses the mother's question?""\n""High-quality afterschool programming during childhood promotes long-term adult mental health\nBackground\nHigh-quality afterschool programming in children has been found to improve standardized test scores, dropout rates, and college attendance.","{'A': 'High-quality afterschool programming has a greater effect on reducing ADHD risk in adults than major depressive disorder risk.', 'B': ""The patient's family history of psychiatric illness prevents any conclusions from being drawn from the study."", 'C': ""High-quality afterschool programming would decrease this patient's risk of developing attention deficit hyperactivity disorder."", 'D': 'High-quality afterschool programming for low-income 8-year-olds may correlate with decreased bipolar disorder risk in adults.', 'E': ""High-quality afterschool programming would decrease this patient's risk of developing major depressive disorder."", 'F': 'High-quality afterschool programming should be free of charge for low-income children to improve adult mental health.', 'G': 'High-quality afterschool programming has a greater effect on reducing psychotic disorder risk in adults than bipolar disorder risk.', 'H': 'High-quality afterschool programming for low-income 8-year-olds may correlate with decreased ADHD risk in adults.'}"
1,D,E,95,"The patient exhibits significant somatic symptoms without any organic cause, which aligns with the clinical presentation of conversion disorder. This condition involves physical symptoms that are believed to be caused by psychological factors rather than a medical illness. The patient's inability to move his arm despite normal vital signs and reflexes, along with his reported exhaustion and dependency on his wife, strongly suggest a psychological basis for his symptoms. Additionally, the rapid withdrawal response to a pin prick test (a sign of hypervigilance) further supports this diagnosis.","A 37-year-old man comes to the emergency department with his wife because of a 3-day history of severe pain in his right arm. He also reports that he cannot move his right arm. The symptoms began after the patient woke up one morning, having slept on his side. He is otherwise healthy. He works as a waiter and says that he feels exhausted from working several night shifts per week. He adds that he “can barely keep his eyes open” when looking after their daughter the next day. Since the onset of the pain, he has been unable to work and is fully dependent on his wife, who took an extra shift to make enough money to pay their monthly bills. The patient appears relaxed but only allows himself to be examined after his wife convinces him. His vital signs are within normal limits. Examination shows 1/5 muscle strength in the right arm. Reflexes are normal. He has no sensation to light touch over the entire right arm and forearm. When a pin prick test is conducted, the patient rapidly withdraws the right arm. Which of the following is the most likely diagnosis?","The symptoms began after the patient woke up one morning, having slept on his side.","{'A': 'Brachial neuritis', 'B': 'Factitious disorder', 'C': 'Somatic symptom disorder', 'D': 'Malingering', 'E': 'Conversion disorder', 'F': 'Radial nerve palsy', 'G': 'Illness anxiety disorder'}"
2,A,F,95,"Given the patient's presentation with hypotension, bradycardia, hypoglycemia (fingerstick blood glucose concentration of 65 mg/dL), prolonged PR intervals, and narrow QRS complexes on ECG, it suggests a possible overdose of an anti-cholinergic agent like atropine or scopolamine. Naloxone is used to reverse the effects of opioid overdose, but in this case, the symptoms align more closely with anticholinergic toxicity. Administering naloxone would be the most appropriate next step to counteract the anticholinergic blockade and potentially improve the patient's respiratory status and heart rate.","A 22-year-old woman is brought to the emergency department 4 hours after the ingestion of 25 tablets of an unknown drug in an attempt to commit suicide. Her temperature is 36.7°C (98°F), pulse is 41/min, respirations are 14/min, and blood pressure is 88/55 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 93%. She is confused and oriented only to person. The pupils are equal and reactive to light. Examination shows cold, clammy extremities. Scattered expiratory wheezing and rhonchi are heard throughout both lung fields. The abdomen is soft. Fingerstick blood glucose concentration is 65 mg/dL. ECG shows prolonged PR intervals and narrow QRS complexes. Two large bore cannulas are inserted and intravenous normal saline, dextrose, and atropine are administered. Five minutes later, pulse is 51/min and blood pressure is 95/61 mm Hg. In addition to securing the airway, which of the following is the most appropriate next step in management?",A 22-year-old woman is brought to the emergency department 4 hours after the ingestion of 25 tablets of an unknown drug in an attempt to commit suicide.,"{'A': 'Glucagon', 'B': 'Activated charcoal', 'C': 'Sodium bicarbonate', 'D': 'Hemodialysis', 'E': 'Pralidoxime', 'F': 'Naloxone', 'G': 'Digoxin-specific antibody'}"
3,B,C,90,"The patient's liver function tests (AST and ALT levels) are elevated at 110 and 115 U/L respectively, which is indicative of possible liver damage or dysfunction. Lamotrigine, while generally well-tolerated, can cause liver enzyme elevations in some patients. Given the patient's recent switch from lithium to lamotrigine, discontinuing lamotrigine would be prudent to assess if the liver enzymes normalize. This action aligns with the most immediate and targeted approach to address the liver function abnormalities observed.","A 63-year-old man comes to the physician for a routine health maintenance examination. He feels well. He has a history of hypertension, atrial fibrillation, bipolar disorder, and osteoarthritis of the knees. Current medications include lisinopril, amiodarone, lamotrigine, and acetaminophen. He started amiodarone 6 months ago and switched from lithium to lamotrigine 4 months ago. The patient does not smoke. He drinks 1–4 beers per week. He does not use illicit drugs. Vital signs are within normal limits. Examination shows no abnormalities. Laboratory studies show:\nSerum\nNa+ 137 mEq/L\nK+ 4.2 mEq/L\nCl- 105 mEq/L\nHCO3- 24 mEq/L\nUrea nitrogen 14 mg/dL\nCreatinine 0.9 mg/dL\nAlkaline phosphatase 82 U/L\nAspartate aminotransferase (AST) 110 U/L\nAlanine aminotransferase (ALT) 115 U/L\nWhich of the following is the most appropriate next step in management?""","Current medications include lisinopril, amiodarone, lamotrigine, and acetaminophen.","{'A': 'Discontinue lisinopril', 'B': 'Discontinue amiodarone', 'C': 'Discontinue lamotrigine', 'D': 'Discontinue acetaminophen', 'E': 'Follow-up laboratory results in 6 months', 'F': 'Follow-up laboratory results in 3 months', 'G': 'Decrease alcohol consumption'}"
4,B,D,90,"The patient's case involves a patient with advanced liver cancer (HCC), a history of alcohol dependence, chronic hepatitis C, and other comorbidities such as hypertension and poorly controlled type 2 diabetes mellitus. While the patient has shown a partial response to Metalimus 100 mg, which is an mTOR inhibitor, the question specifically mentions that she is considering Noxbinle (tumorolimus) for its purported survival benefit. \n\nGiven the patient's history of alcohol use disorder and hepatitis C, which are known risk factors for liver disease progression, it is reasonable to consider the potential benefits and risks of Noxbinle. However, the advertisement for Noxbinle claims a survival benefit compared to Metalimus 100 mg, which aligns with the patient's interest in potentially improving her prognosis.\n\nThe patient's current regimen includes enalapril for hypertension and insulin for diabetes management. Starting Noxbinle would require careful consideration of potential interactions and side effects, especially since she already has a history of poorly controlled diabetes. Nevertheless, the claim of a survival benefit from the advertisement suggests that starting Noxbinle 100 mg might be a reasonable step, assuming no contraindications or significant adverse effects are present.\n\nTherefore, based on the information provided, the most accurate statement is that the patient should start Noxbinle 100 mg because of the survival benefit relative to Metalimus 100 mg.","A patient with HCC and a long history of alcohol dependence and chronic hepatitis C has been using the mTOR inhibitor Metalimus 100 mg for cancer treatment. Her cancer has shown a partial response. She also has a history of hypertension and poorly controlled type 2 diabetes mellitus complicated by diabetic retinopathy. Current medications include enalapril and insulin. She asks her oncologist and hepatologist if she could try Noxbinle (tumorolimus) for its purported survival benefit in treating HCC. Based on the data provided in the drug advertisement, which of the following statements is most accurate?",A patient with HCC and a long history of alcohol dependence and chronic hepatitis C has been using the mTOR inhibitor Metalimus 100 mg for cancer treatment.,"{'A': 'The patient is not a good candidate for Noxbinle due to her history of hypertension', 'B': 'The patient is not a good candidate for Noxbinle due to her history of diabetes', 'C': 'The patient should start Noxbinle 50 mg because of the survival benefit relative to Metalimus 100 mg', 'D': 'The patient should start Noxbinle 100 mg because of the survival benefit relative to Metalimus 100 mg', 'E': 'The patient should start Noxbinle 50 mg because of her history of alcohol use disorder and hepatitis C', 'F': 'The patient should start Noxbinle 25 mg because of the low risk of adverse effects while retaining a survival benefit relative to Metalimus 100 mg'}"

In [15]:
df_a[['answer', 'parsed_answer', 'confidence', 'evidence']]

,answer,parsed_answer,confidence,evidence
0,H,H,95,"The provided information clearly states that the study found a significant reduction in the risk of ADHD (attention deficit hyperactivity disorder) among participants who received afterschool enrichment compared to those in the control group. Specifically, the hazard ratio for ADHD was 0.80 (95% CI: 0.74–0.92), indicating a 20% lower risk of developing ADHD in adulthood for those who participated in the program. This directly supports option H, which suggests that high-quality afterschool programming for low-income 8-year-olds may correlate with decreased ADHD risk in adults."
1,D,D,95,"The patient's symptoms (severe pain, inability to move the arm, and rapid withdrawal reflex) align closely with malingering. Malingering involves intentionally producing false or grossly exaggerated physical symptoms for non-medical gain, such as financial compensation or avoiding work responsibilities. Given the patient's reported exhaustion from working multiple night shifts, his need for his wife to take an extra shift, and his apparent reluctance to be examined, these behaviors suggest a possible motive for malingering. Additionally, the sudden onset of symptoms without any clear organic cause further supports this diagnosis. Options like radian nerve palsy or conversion disorder typically present with more gradual onset and specific neurological deficits, which do not fit the described scenario."
2,A,A,95,"Given the patient's symptoms including confusion, hypotension, hypoglycemia (fingerstick blood glucose concentration of 65 mg/dL), and respiratory findings (wheezing and rhonchi), it is crucial to address the hypoglycemia first. Glucagon is the most appropriate initial treatment for severe hypoglycemia as it rapidly raises blood glucose levels. The other options do not directly address the immediate life-threatening condition presented by the patient."
3,B,B,95,"The patient has been taking amiodarone for 6 months, which can cause elevated liver enzymes as a side effect. His AST and ALT levels are both elevated at 110 and 115 U/L respectively, indicating possible liver damage or dysfunction. Given his history of bipolar disorder and the need to monitor his medications carefully, discontinuing amiodarone would be the most immediate and appropriate action to address this finding."
4,B,B,95,"The patient's history of poorly controlled type 2 diabetes mellitus complicated by diabetic retinopathy is a significant contraindication for the use of Tumorolimus (Noxbinle). This is because Tumorolimus is an immunotherapy that can exacerbate pre-existing conditions such as diabetes, potentially leading to severe complications like diabetic retinopathy. Therefore, based on the information provided, the patient is not a good candidate for Noxbinle due to her history of diabetes."